import { getBodyTemplates } from "@/features/sources";
import { requireUser } from "@/lib/auth/require-user.server";
import { AppLink } from "@/shared/components/app-button";
import { PageHeader } from "@/shared/components/page-header";
import { PrivateImage } from "@/shared/components/private-image";

export default async function ProfilePage() {
  const [{ user }, templates] = await Promise.all([requireUser(), getBodyTemplates()]);
  const displayName = typeof user.user_metadata.full_name === "string" ? user.user_metadata.full_name : "Fitly member";
  return <><PageHeader eyebrow="Your Fitly" title="Profile" description="One account across Fitly mobile and web, with separate private image libraries." actions={<AppLink href="/settings" secondary>Settings</AppLink>} /><div className="mx-auto grid max-w-[1050px] gap-6 px-5 py-8 sm:px-8 lg:grid-cols-[.7fr_1.3fr] lg:px-12"><section className="self-start rounded-[28px] bg-ink-deep p-7 text-surface"><div className="flex size-14 items-center justify-center rounded-2xl bg-marigold font-display text-2xl font-extrabold text-ink">{displayName.charAt(0).toUpperCase()}</div><h2 className="font-display mt-5 text-2xl font-extrabold">{displayName}</h2><p className="mt-1 text-sm text-surface/55">{user.email}</p><p className="mt-6 text-xs leading-5 text-surface/55">Your identity and daily quota are shared with mobile. Photos and generated looks are not.</p></section><section className="rounded-[28px] bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-extrabold tracking-[.14em] text-violet uppercase">Body templates</p><h2 className="font-display mt-1 text-2xl font-extrabold">Your reusable mirror</h2></div><span className="text-xs font-bold text-text-tertiary">{templates.length}/5</span></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3">{templates.map((template) => <article key={template.id} className="overflow-hidden rounded-[20px] bg-surface"><div className="relative aspect-[4/5]"><PrivateImage kind="body-template" id={template.id} alt={template.name} /></div><div className="p-3"><p className="truncate text-xs font-bold">{template.name}</p><p className="mt-1 text-[10px] text-text-tertiary">{template.pose === "full" ? "Full body" : "Waist up"}</p></div></article>)}<AppLink href="/try-on/body" secondary>Add template</AppLink></div></section></div></>;
}
